lib/learn_phoenix_web/router.ex
defmodule LearnPhoenixWeb.Router do
  use LearnPhoenixWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug LearnPhoenixWeb.Plugs.LoadUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LearnPhoenixWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/about", PageController, :about
    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/contractlist", ContractController, :contractlist
    post "/contractlist", ContractController, :contractlist
    get "/logout", SessionController, :delete
    get "/addcontract", ContractController, :newcontract
    post "/addcontract", ContractController, :createcontract
    get "editcontract/:id", ContractController, :editcontract
    get "viewcontract/:id", ContractController, :viewcontract
    get "deletecontract/:id", ContractController, :deletecontract
    put "updatecontract/:id", ContractController, :updatecontract
    put "deletecontract/:id",ContractController, :deletecontract
  end

  # Other scopes may use custom stacks.
  # scope "/api", LearnPhoenixWeb do
  #   pipe_through :api
  # end
end

lib/learn_phoenix_web/views/layout_view.ex
defmodule LearnPhoenixWeb.LayoutView do
  use LearnPhoenixWeb, :view
end

lib/learn_phoenix_web/templates/layout/app.html.eex
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Welcome User</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <%= render "app_nav.html", conn: @conn, user: @current_user %>
    <br><br>
    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/learn_phoenix_web/templates/layout/app_nav.html.eex
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
    </div>
    <div class="collapse navbar-collapse" id="primary-nav">
      <ul class="nav navbar-nav">

      </ul>

      <!-- add code from here -->
      <ul class="nav navbar-nav navbar-right">
        <%= if @user do %>
          <li class="dropdown">
            <a href="/logout" class="dropdown-toggle" data-toggle="dropdown">Logout</a>
            <ul class="dropdown-menu">
              <li><%= link "Log Out", to: "/logout" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link "Register", to: registration_path(@conn, :new), class: "nav-link" %></li>
          <li><%= link "Sign in", to: session_path(@conn, :new), class: "nav-link" %></li>
        <% end %>
      </ul>
      <!-- Upto here -->
    </div>
</div>
</nav>